name: CD

on:
  push:
    branch:
      - master
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Build
      run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Sync to S3
      env:
        PRODUCTION: ${{ secrets.AWS_PRODUCTION_ACCOUNT_ID }}
        TESTING: ${{ secrets.AWS_TESTING_ACCOUNT_ID }}
      run: |
        ACCOUNT_ID=$([[ $GITHUB_REF == 'master' ]] && echo $PRODUCTION || echo $TESTING)
        CREDENTIALS=$(aws sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_ID}:role/cd_web" --role-session-name "CD" --duration-seconds 900)
        export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | cut -d '"' -f 28)
        export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | cut -d '"' -f 16)
        export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | cut -d '"' -f 20)
        BUCKET="bitelio.$([[ $GITHUB_REF == 'master' ]] && echo com || echo dev)"
        npx aws s3 sync dist "s3://${BUCKET}" --size-only --delete
